import { change as changeStandardReservations } from "@features/zones/standardReservationsSlice";
import { change as changeAccommodationReservations } from "@features/zones/accommodationReservationsSlice";
import { change as changeNomenclatures } from "@features/zones/nomenclaturesSlice";
import { change as changeZones } from "@features/zones/informationSlice";
import { change as changeTables } from "@features/tables/informationSlice";
import { change as changeOrders } from "@features/tables/ordersSlice";
import { change as changeEconomy } from "@features/function/economySlice";
import { change as changeMenu } from "@features/tables/menuSlice";
import { change as changeKitchen } from "@features/tables/kitchenSlice";
import { change as changeRoster } from "@features/function/rosterSlice";
import { change as changeCustomers } from "@features/people/customersSlice";
import { change as changeSuppliers } from "@features/people/suppliersSlice";
import { change as changeInventory } from "@features/inventory/informationSlice";
import { change as changeProducts } from "@features/sales/productsSlice";
import { change as changeSales } from "@features/sales/salesSlice";
import { change as changeAccommodationOptions } from "@features/zones/accommodationOptionsSlice";
import { change as changeGroups } from "@features/sales/groupsSlice";
import { change as changeRecipes } from "@features/sales/recipesSlice";
import { change as changeBills } from "@features/people/billsSlice";

export default changeGeneralInformation = (dispatch, data) => {
  dispatch(changeZones(data.zones));
  dispatch(changeAccommodationReservations(data.accommodation));
  dispatch(changeStandardReservations(data.standard));
  dispatch(changeNomenclatures(data.nomenclatures));
  dispatch(changeTables(data.tables));
  dispatch(changeOrders(data.orders));
  dispatch(changeEconomy(data.economy));
  dispatch(changeMenu(data.menu));
  dispatch(changeKitchen(data.kitchen));
  dispatch(changeRoster(data.roster));
  dispatch(changeCustomers(data.customers));
  dispatch(changeSuppliers(data.suppliers));
  dispatch(changeInventory(data.inventory));
  dispatch(changeProducts(data.products));
  dispatch(changeSales(data.sales));
  dispatch(changeAccommodationOptions(data.accommodationOptions));
  dispatch(changeGroups(data.groups));
  dispatch(changeRecipes(data.recipes));
  dispatch(changeBills(data.bills));
};
