import { clean as cleanUser } from "@features/user/informationSlice";
import { clean as cleanReservations } from "@features/groups/reservationsSlice";
import { clean as cleanNomenclatures } from "@features/groups/nomenclaturesSlice";
import { clean as cleanGroups } from "@features/groups/informationSlice";
import { clean as cleanHelpers } from "@features/helpers/informationSlice";
import { clean as cleanTables } from "@features/tables/informationSlice";
import { clean as cleanOrders } from "@features/tables/ordersSlice";
import { clean as cleanKitchen } from "@features/tables/kitchenSlice";
import { clean as cleanMenu } from "@features/tables/menuSlice";
import { clean as cleanEconomy } from "@features/function/economySlice";
import { inactive as inactiveSession } from "@features/user/sessionSlice";
import { inactive as inactiveGroup } from "@features/function/informationSlice";
import { clean as cleanRoster } from "@features/function/rosterSlice";
import { clean as cleanPeople } from "@features/function/peopleSlice";
import { clean as cleanInventory } from '@features/inventory/informationSlice';
import { clean as cleanProducts } from "@features/sales/productsSlice";
import { clean as cleanSales } from "@features/sales/salesSlice";
import { clean as cleanAccommodations } from "@features/groups/accommodationsSlice";

export default cleanData = (dispatch) => {
  dispatch(inactiveSession());
  dispatch(inactiveGroup());
  dispatch(cleanUser());
  dispatch(cleanReservations());
  dispatch(cleanNomenclatures());
  dispatch(cleanGroups());
  dispatch(cleanHelpers());
  dispatch(cleanTables());
  dispatch(cleanOrders());
  dispatch(cleanEconomy());
  dispatch(cleanMenu());
  dispatch(cleanKitchen());
  dispatch(cleanRoster());
  dispatch(cleanPeople());
  dispatch(cleanInventory());
  dispatch(cleanProducts());
  dispatch(cleanSales());
  dispatch(cleanAccommodations());
};