import { clean as cleanUser } from "@features/user/informationSlice";
import { clean as cleanStandardReservations } from "@features/zones/standardReservationsSlice";
import { clean as cleanAccommodationReservations } from "@features/zones/accommodationReservationsSlice";
import { clean as cleanNomenclatures } from "@features/zones/nomenclaturesSlice";
import { clean as cleanZones } from "@features/zones/informationSlice";
import { clean as cleanHelpers } from "@features/helpers/informationSlice";
import { clean as cleanTables } from "@features/tables/informationSlice";
import { clean as cleanOrders } from "@features/tables/ordersSlice";
import { clean as cleanKitchen } from "@features/tables/kitchenSlice";
import { clean as cleanMenu } from "@features/tables/menuSlice";
import { clean as cleanEconomy } from "@features/function/economySlice";
import { inactive as inactiveSession } from "@features/user/sessionSlice";
import { inactive as inactiveGroup } from "@features/helpers/statusSlice";
import { clean as cleanRoster } from "@features/function/rosterSlice";
import { clean as cleanCustomers } from "@features/people/customersSlice";
import { clean as cleanSuppliers } from "@features/people/suppliersSlice";
import { clean as cleanInventory } from "@features/inventory/informationSlice";
import { clean as cleanProducts } from "@features/sales/productsSlice";
import { clean as cleanSales } from "@features/sales/salesSlice";
import { clean as cleanAccommodationOptions } from "@features/zones/accommodationOptionsSlice";
import { clean as cleanGroups } from "@features/sales/groupsSlice";
import { clean as cleanRecipes } from "@features/sales/recipesSlice";
import { clean as cleanBills } from "@features/people/billsSlice";

export default cleanData = (dispatch) => {
  dispatch(inactiveSession());
  dispatch(inactiveGroup());
  dispatch(cleanUser());
  dispatch(cleanStandardReservations());
  dispatch(cleanAccommodationReservations());
  dispatch(cleanNomenclatures());
  dispatch(cleanZones());
  dispatch(cleanHelpers());
  dispatch(cleanTables());
  dispatch(cleanOrders());
  dispatch(cleanEconomy());
  dispatch(cleanMenu());
  dispatch(cleanKitchen());
  dispatch(cleanRoster());
  dispatch(cleanCustomers());
  dispatch(cleanSuppliers());
  dispatch(cleanInventory());
  dispatch(cleanProducts());
  dispatch(cleanSales());
  dispatch(cleanAccommodationOptions());
  dispatch(cleanGroups());
  dispatch(cleanRecipes());
  dispatch(cleanBills());
};
